from django.contrib import admin

# Register your models here.
from .models import *

admin.site.register(assigned_users)
admin.site.register(bug)
admin.site.register(bug_client)
admin.site.register(contact_history)
admin.site.register(costs)
admin.site.register(customers)
admin.site.register(customers_campus)
admin.site.register(documents)
admin.site.register(documents_folder)
admin.site.register(document_permissions)
admin.site.register(email_content)
admin.site.register(email_contact)
admin.site.register(folders)
admin.site.register(group_permissions)
admin.site.register(groups)
admin.site.register(kanban_board)
admin.site.register(kanban_comment)
admin.site.register(kanban_card)
admin.site.register(kanban_column)
admin.site.register(kanban_level)
admin.site.register(list_of_amount_type)
admin.site.register(list_of_bug_client)
admin.site.register(list_of_currency)
admin.site.register(list_of_contact_types)
admin.site.register(list_of_countries_regions)
admin.site.register(list_of_countries)
admin.site.register(list_of_lead_source)
admin.site.register(list_of_opportunity_stage)
admin.site.register(list_of_quote_stages)
admin.site.register(list_of_requirement_item_status)
admin.site.register(list_of_requirement_item_type)
admin.site.register(list_of_requirement_status)
admin.site.register(list_of_taxes)
admin.site.register(list_of_titles)
admin.site.register(opportunity)
admin.site.register(opportunity_permissions)
admin.site.register(organisations)
admin.site.register(organisations_campus)
admin.site.register(permission_set)
admin.site.register(products_and_services)
admin.site.register(project_customers)
admin.site.register(project_groups)
admin.site.register(project_history)
admin.site.register(project_opportunity)
admin.site.register(project_stages)
admin.site.register(project_tasks)
admin.site.register(project)
admin.site.register(quotes)
admin.site.register(quotes_products_and_services)
admin.site.register(requirements)
admin.site.register(requirement_item)
admin.site.register(requirement_item_links)
admin.site.register(requirement_links)
admin.site.register(requirement_permissions)
admin.site.register(quote_responsible_customers)
admin.site.register(stages)
admin.site.register(tasks_actions)
admin.site.register(tasks_customers)
admin.site.register(tasks_groups)
admin.site.register(tasks_history)
admin.site.register(tasks)
admin.site.register(to_do)
admin.site.register(user_groups)






