# Generated by Django 4.1.4 on 2023-01-22 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("NearBeach", "0002_initialise_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changetask",
            name="change_task_status",
            field=models.IntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Waiting for approval"),
                    (3, "Approved"),
                    (4, "Started"),
                    (5, "Finished"),
                    (6, "Rejected"),
                    (7, "Paused"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="UserProfilePicture",
            fields=[
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "change_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_change_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NearBeach.document",
                    ),
                ),
            ],
            options={
                "db_table": "user_profile_picture",
            },
        ),
    ]
