# Generated by Django 2.1.5 on 2019-02-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='organisation_id',
        ),
    ]
