# Generated by Django 2.1.5 on 2019-03-24 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_for_change_note',
            fields=[
                ('rfc_note_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfc_note', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_for_change_note_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_for_change_note',
            },
        ),
    ]
