# Generated by Django 2.1.7 on 2020-03-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_task',
            name='change_user',
        ),
        migrations.RemoveField(
            model_name='project_task',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project_task',
            name='task_id',
        ),
        migrations.AddField(
            model_name='kanban_board',
            name='kanban_board_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
        migrations.DeleteModel(
            name='project_task',
        ),
    ]
