# Generated by Django 2.1.7 on 2020-09-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_requirement_item_status',
            name='requirement_item_status_is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
