# Generated by Django 2.1 on 2018-12-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='kudos_key',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
    ]
