# Generated by Django 2.2.7 on 2020-03-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20200308_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_assignment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customer'),
        ),
        migrations.AddField(
            model_name='object_assignment',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisation'),
        ),
    ]
