# Generated by Django 2.1 on 2018-12-15 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20181215_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kudos',
            name='kudos_id',
        ),
        migrations.AlterField(
            model_name='kudos',
            name='kudos_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
