# Generated by Django 2.1.7 on 2020-09-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_list_of_requirement_item_status_requirement_item_status_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_of_requirement_item_status',
            old_name='requirement_item_status_is_closed',
            new_name='status_is_closed',
        ),
    ]
