# Generated by Django 2.2.7 on 2020-04-19 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20200329_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_permission',
            name='whiteboard_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.whiteboard'),
        ),
    ]
