# Generated by Django 4.1.4 on 2023-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "NearBeach",
            "0004_rename_kanban_property_kanbancolumn_kanban_column_property",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kanbancard",
            name="kanban_card_priority",
            field=models.IntegerField(
                choices=[
                    (0, "Highest"),
                    (1, "High"),
                    (2, "Normal"),
                    (3, "Low"),
                    (4, "Lowest"),
                ],
                default=2,
            ),
        ),
    ]
