# Generated by Django 3.0.5 on 2020-09-26 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20200917_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_note',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisation'),
        ),
        migrations.AlterModelTable(
            name='object_note',
            table='object_note',
        ),
    ]
