# Generated by Django 2.1.7 on 2019-08-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_requirement_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement_customer',
            name='requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirement'),
            preserve_default=False,
        ),
    ]
