# Generated by Django 2.1.5 on 2019-02-26 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0004_opportunity_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_for_change',
            fields=[
                ('request_for_change_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_for_change_title', models.CharField(max_length=255)),
                ('request_for_change_summary', tinymce.models.HTMLField(verbose_name='request_for_change_summary')),
                ('request_for_change_type', models.IntegerField(choices=[(4, 'Emergency'), (3, 'High'), (2, 'Medium'), (1, 'Low')])),
                ('request_for_change_implementation_start_date', models.DateTimeField()),
                ('request_for_change_implementation_end_date', models.DateTimeField()),
                ('request_for_change_implementation_release_date', models.DateTimeField()),
                ('request_for_change_version_number', models.CharField(max_length=25)),
                ('request_for_change_status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Waiting for approval'), (3, 'Approved'), (4, 'Started'), (5, 'Finished')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_for_change_change_user', to=settings.AUTH_USER_MODEL)),
                ('request_for_change_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_for_change_lead', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_for_change',
            },
        ),
    ]
