# Generated by Django 2.1 on 2018-12-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_kudos_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customer'),
        ),
        migrations.AddField(
            model_name='folder',
            name='organisation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisation'),
        ),
    ]
