# Generated by Django 2.2.7 on 2020-01-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_requirement_customer_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_assignment',
            name='requirement_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirement_item'),
        ),
    ]
