# Generated by Django 2.1.5 on 2019-02-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_request_for_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_for_change',
            name='request_for_change_impact',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=1),
        ),
        migrations.AddField(
            model_name='request_for_change',
            name='request_for_change_priority',
            field=models.IntegerField(choices=[(4, 'Critical'), (3, 'High'), (2, 'Medium'), (1, 'Low')], default=1),
        ),
        migrations.AddField(
            model_name='request_for_change',
            name='request_for_change_risk',
            field=models.IntegerField(choices=[(5, 'Very High'), (4, 'High'), (3, 'Moderate'), (2, 'Low'), (1, 'None')], default=1),
        ),
    ]
