# Generated by Django 2.1.5 on 2019-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_auto_20190228_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_set',
            name='tag',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read Only'), (2, 'Edit Only'), (3, 'Add and Edit'), (4, 'Full Permission')], default=0),
        ),
        migrations.AlterField(
            model_name='change_task',
            name='change_task_status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Waiting for approval'), (3, 'Approved'), (4, 'Started'), (5, 'Finished'), (6, 'Rejected')]),
        ),
        migrations.AlterField(
            model_name='request_for_change',
            name='rfc_status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Waiting for approval'), (3, 'Approved'), (4, 'Started'), (5, 'Finished'), (6, 'Rejected')]),
        ),
    ]
