# Generated by Django 2.1.5 on 2019-02-26 07:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0006_auto_20190226_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_for_change',
            name='request_for_change_backout_plan',
            field=tinymce.models.HTMLField(default='a', verbose_name='request_for_change_backout_plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_for_change',
            name='request_for_change_implementation_plan',
            field=tinymce.models.HTMLField(default='', verbose_name='request_for_change_implementation_plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_for_change',
            name='request_for_change_risk_and_impact_analysis',
            field=tinymce.models.HTMLField(default='a', verbose_name='request_for_change_risk_and_impact_analysis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_for_change',
            name='request_for_change_test_plan',
            field=tinymce.models.HTMLField(default='a', verbose_name='request_for_change_test_plan'),
            preserve_default=False,
        ),
    ]
