# Generated by Django 2.1.7 on 2019-05-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0006_auto_20190405_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='equirement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirement_item'),
        ),
    ]
