# Generated by Django 3.0.5 on 2020-05-25 04:31

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0006_auto_20200521_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='creation_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_creation_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
