# Generated by Django 4.1.4 on 2023-03-08 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0006_objectassignment_link_relationship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectassignment",
            name="change_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.changetask",
            ),
        ),
        migrations.AlterField(
            model_name="objectassignment",
            name="link_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Block", "Block"),
                    ("Duplicate", "Duplicate"),
                    ("Relate", "Relate"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="objectassignment",
            name="parent_link",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
