# Generated by Django 2.1.5 on 2019-03-12 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0006_auto_20190307_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement_link',
            name='opportunity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.opportunity'),
        ),
    ]
