# Generated by Django 2.1.5 on 2019-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_auto_20190226_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_change',
            name='request_for_change_version_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
