# Generated by Django 3.0.5 on 2020-05-25 05:01

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0007_opportunity_creation_user'),
    ]

    operations = [

    ]
