# Generated by Django 2.1.7 on 2019-05-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_folder_equirement_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='equirement_item',
            new_name='requirement_item',
        ),
    ]
