# Generated by Django 3.1.2 on 2021-04-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_kanban_card_kanban_card_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission_set',
            old_name='kanban',
            new_name='kanban_board',
        ),
    ]
