# Generated by Django 4.1.4 on 2023-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0007_objectassignment_change_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectassignment",
            name="link_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Block", "Block"),
                    ("Duplicate", "Duplicate"),
                    ("Relate", "Relate"),
                    ("Subobject", "Subobject"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
