# Generated by Django 2.2.7 on 2020-02-13 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0007_change_task_change_task_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='whiteboard',
            fields=[
                ('whiteboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('whiteboard_title', models.CharField(max_length=255)),
                ('whiteboard_xml', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whiteboard',
            },
        ),
        migrations.AddField(
            model_name='object_assignment',
            name='whiteboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.whiteboard'),
        ),
    ]
