# Generated by Django 2.1.7 on 2019-08-19 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0008_auto_20190526_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='nearbeach_option',
            fields=[
                ('nearbeach_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_point_hour_min', models.IntegerField(default=4)),
                ('story_point_hour_max', models.IntegerField(default=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearbeach_option_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nearbeach_option',
            },
        ),
        migrations.CreateModel(
            name='timesheet',
            fields=[
                ('timesheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('timesheet_description', models.CharField(blank=True, max_length=255, null=True)),
                ('timesheet_date', models.DateField()),
                ('timesheet_start_time', models.TimeField()),
                ('timesheet_end_time', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timesheet',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_story_point_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='project',
            name='project_story_point_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_story_point_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_story_point_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requirement_item',
            name='ri_story_point_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='requirement_item',
            name='ri_story_point_min',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='task',
            name='task_story_point_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='task_story_point_min',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.project'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='requirement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirement_item'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.task'),
        ),
    ]
