# Generated by Django 2.2.7 on 2020-02-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_auto_20200213_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_set',
            name='whiteboard',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read Only'), (2, 'Edit Only'), (3, 'Add and Edit'), (4, 'Full Permission')], default=0),
        ),
    ]
