# Generated by Django 2.1.7 on 2019-07-30 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0008_auto_20190526_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='nearbeach_option',
            fields=[
                ('nearbeach_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_point_hour_min', models.IntegerField(default=4)),
                ('story_point_hour_max', models.IntegerField(default=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearbeach_option_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nearbeach_option',
            },
        ),
    ]


def initialise_data(apps, schema_editor):
    #AInitialise the data
    db_alias = schema_editor.connection.alias

    nearbeach_option = apps.get_model("NearBeach", "nearbeach_option")
    nearbeach_option.objects.using(db_alias).bulk_create([
        nearbeach_option(story_point_hour_min=4),

    ])




