# Generated by Django 3.0.5 on 2020-09-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_auto_20200831_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object_note',
            old_name='opportunity_id',
            new_name='opportunity',
        ),
        migrations.RenameField(
            model_name='object_note',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='object_note',
            old_name='quote_id',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='object_note',
            old_name='requirement_id',
            new_name='requirement',
        ),
        migrations.RenameField(
            model_name='object_note',
            old_name='requirement_item_id',
            new_name='requirement_item',
        ),
        migrations.RenameField(
            model_name='object_note',
            old_name='task_id',
            new_name='task',
        ),
    ]
