# Generated by Django 2.1.5 on 2019-02-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_auto_20190226_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_set',
            name='request_for_change',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read Only'), (2, 'Edit Only'), (3, 'Add and Edit'), (4, 'Full Permission')], default=0),
        ),
    ]
