# Generated by Django 4.1.1 on 2023-04-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0008_alter_objectassignment_link_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpermission",
            name="kanban_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.kanbancard",
            ),
        ),
        migrations.AlterField(
            model_name="objectassignment",
            name="link_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("block", "Block"),
                    ("duplicate", "Duplicate"),
                    ("relate", "Relate"),
                    ("subobject", "Subobject"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
