# Generated by Django 2.1.7 on 2019-08-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0009_nearbeach_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_story_point_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='project',
            name='project_story_point_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_story_point_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_story_point_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_story_point_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='task',
            name='task_story_point_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='nearbeach_option',
            name='story_point_hour_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='nearbeach_option',
            name='story_point_hour_min',
            field=models.IntegerField(default=1),
        ),
    ]
