# Generated by Django 2.1.7 on 2020-02-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0009_permission_set_whiteboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='whiteboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.whiteboard'),
        ),
    ]
