# Generated by Django 4.1.1 on 2023-04-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0009_documentpermission_kanban_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="kanban_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.kanbancard",
            ),
        ),
    ]
