# Generated by Django 2.1.5 on 2019-01-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0009_auto_20190130_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission_set',
            name='permission_set_name',
            field=models.CharField(max_length=255),
        ),
    ]
