# Generated by Django 2.1.5 on 2019-02-27 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0010_auto_20190227_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_assignment',
            name='request_for_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.request_for_change'),
        ),
    ]
