# Generated by Django 4.1.1 on 2023-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0010_folder_kanban_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionset",
            name="tag",
            field=models.IntegerField(
                choices=[
                    (0, "No Permission"),
                    (1, "Read Only"),
                    (2, "Edit Only"),
                    (3, "Add and Edit"),
                    (4, "Full Permission"),
                ],
                default=0,
            ),
        ),
    ]
