# Generated by Django 3.0.5 on 2020-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0010_auto_20200901_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_user',
            name='about_user_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='change_task',
            name='change_task_description',
            field=models.TextField(verbose_name='change_task_description'),
        ),
        migrations.AlterField(
            model_name='contact_history',
            name='contact_history',
            field=models.TextField(verbose_name='contact_history'),
        ),
        migrations.AlterField(
            model_name='email_content',
            name='email_content',
            field=models.TextField(verbose_name='email_content'),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='improvement_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='liked_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_description',
            field=models.TextField(verbose_name='oppertunity_description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(verbose_name='project_description'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote_template',
            name='company_letter_head',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote_template',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote_template',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote_template',
            name='organisation_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote_template',
            name='payment_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request_for_change',
            name='rfc_backout_plan',
            field=models.TextField(verbose_name='rfc_backout_plan'),
        ),
        migrations.AlterField(
            model_name='request_for_change',
            name='rfc_implementation_plan',
            field=models.TextField(verbose_name='rfc_implementation_plan'),
        ),
        migrations.AlterField(
            model_name='request_for_change',
            name='rfc_risk_and_impact_analysis',
            field=models.TextField(verbose_name='rfc_risk_and_impact_analysis'),
        ),
        migrations.AlterField(
            model_name='request_for_change',
            name='rfc_summary',
            field=models.TextField(verbose_name='rfc_summary'),
        ),
        migrations.AlterField(
            model_name='request_for_change',
            name='rfc_test_plan',
            field=models.TextField(verbose_name='rfc_test_plan'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_long_description',
            field=models.TextField(),
        ),
    ]
