# Generated by Django 4.2.4 on 2023-09-03 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("NearBeach", "0011_permissionset_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "user_setting_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("DASHBOARD", "Dashboard"),
                            ("EDIT_KANBAN_BOARD", "Edit Kanban Board"),
                            ("KANBAN_BOARD", "Kanban Board"),
                            ("SEARCH", "Search"),
                            ("THEME", "NearBeach Theme"),
                        ],
                        default="THEME",
                        max_length=30,
                    ),
                ),
                ("setting_data", models.JSONField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
