# Generated by Django 2.1.5 on 2019-02-28 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0011_object_assignment_request_for_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_permission',
            name='request_for_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.request_for_change'),
        ),
        migrations.AddField(
            model_name='folder',
            name='request_for_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.request_for_change'),
        ),
        migrations.AddField(
            model_name='folder',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirement'),
        ),
    ]
