# Generated by Django 3.2.5 on 2021-09-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0011_auto_20210825_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_assignment',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='tag_assignment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tag_assignment',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='tag_assignment',
            name='task',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_colour',
            field=models.CharField(default='ff69b4', max_length=6),
        ),
        migrations.AddField(
            model_name='tag_assignment',
            name='object_enum',
            field=models.CharField(choices=[('REQ', 'Requirement'), ('ITEM', 'Requirement Item'), ('PRO', 'Project'), ('TASK', 'Task'), ('KAN', 'Kanban Board'), ('CARD', 'Kanban Card'), ('RFC', 'Reuqest for Change'), ('CUST', 'Customer'), ('ORG', 'Organisation')], default='REQ', max_length=4),
        ),
        migrations.AddField(
            model_name='tag_assignment',
            name='object_id',
            field=models.IntegerField(default=0),
        ),
    ]
