# Generated by Django 2.1.7 on 2019-08-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0011_auto_20190805_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement_item',
            old_name='task_story_point_max',
            new_name='ri_story_point_max',
        ),
        migrations.RenameField(
            model_name='requirement_item',
            old_name='task_story_point_min',
            new_name='ri_story_point_min',
        ),
    ]
