# Generated by Django 2.1.7 on 2019-08-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0012_auto_20190805_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_story_point_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_story_point_min',
            field=models.IntegerField(default=4),
        ),
    ]
