# Generated by Django 2.1.5 on 2019-02-28 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0012_auto_20190228_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_task',
            fields=[
                ('change_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_task_title', models.CharField(max_length=255)),
                ('change_task_description', tinymce.models.HTMLField(verbose_name='change_task_description')),
                ('change_task_start_date', models.DateTimeField()),
                ('change_task_end_date', models.DateTimeField()),
                ('change_required_by', models.CharField(default='Stakeholder(s)', max_length=255)),
                ('change_status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Waiting for approval'), (3, 'Approved'), (4, 'Started'), (5, 'Finished')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_assigned_user', to=settings.AUTH_USER_MODEL)),
                ('change_qa_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_qa_user', to=settings.AUTH_USER_MODEL)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_task_change_user', to=settings.AUTH_USER_MODEL)),
                ('request_for_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.request_for_change')),
            ],
            options={
                'db_table': 'change_task',
            },
        ),
    ]
