# Generated by Django 4.2.4 on 2023-10-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0012_usersetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpermission",
            name="new_object",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
