# Generated by Django 2.1.5 on 2019-02-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0013_change_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change_task',
            old_name='change_assigned_user',
            new_name='change_task_assigned_user',
        ),
        migrations.RenameField(
            model_name='change_task',
            old_name='change_qa_user',
            new_name='change_task_qa_user',
        ),
        migrations.RenameField(
            model_name='change_task',
            old_name='change_required_by',
            new_name='change_task_required_by',
        ),
        migrations.RenameField(
            model_name='change_task',
            old_name='change_status',
            new_name='change_task_status',
        ),
    ]
