# Generated by Django 2.1.7 on 2019-08-08 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0013_auto_20190808_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='timesheet',
            fields=[
                ('timesheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('timesheet_description', models.CharField(blank=True, max_length=255, null=True)),
                ('timesheet_date', models.DateField()),
                ('timesheet_start_time', models.TimeField()),
                ('timesheet_end_time', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timesheet',
            },
        ),
    ]
