# Generated by Django 4.2.4 on 2023-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0014_alter_notification_notification_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
