# Generated by Django 5.0 on 2023-12-11 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0018_publiclink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publiclink",
            name="public_link_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
