# Generated by Django 4.1.1 on 2022-10-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0020_remove_request_for_change_rfc_status_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_user',
            name='about_user_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='change_task',
            name='change_task_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_url_location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='kanban_card',
            name='kanban_card_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='improvement_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='liked_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='object_note',
            name='object_note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='request_for_change_note',
            name='rfc_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='requirement_item',
            name='requirement_item_scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='whiteboard',
            name='whiteboard_xml',
            field=models.TextField(blank=True, default=''),
        ),
    ]
