# Generated by Django 4.1.1 on 2022-11-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0021_alter_about_user_about_user_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="campus_address1",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campus",
            name="campus_address2",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campus",
            name="campus_address3",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campus",
            name="campus_fax",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="campus",
            name="campus_phone",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="campus",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.customer",
            ),
        ),
        migrations.AlterField(
            model_name="list_of_country_region",
            name="region_type",
            field=models.CharField(blank=True, default="", max_length=80, null=True),
        ),
    ]
