# Generated by Django 5.0 on 2023-12-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0022_project_status_task_status_switch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changetask",
            name="change_task_status",
            field=models.IntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Waiting for approval"),
                    (3, "Approved"),
                    (4, "Started"),
                    (5, "Finished"),
                    (6, "Rejected"),
                    (7, "Paused"),
                    (8, "Ready for QA"),
                    (9, "Failed"),
                ]
            ),
        ),
    ]
