# Generated by Django 4.1.1 on 2022-11-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "NearBeach",
            "0023_remove_quote_change_user_remove_quote_creation_user_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "UPDATE customer SET customer_profile_picture=null WHERE 1=1"
                )
            ]
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_profile_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.document",
            ),
        ),
    ]
