# Generated by Django 5.0.1 on 2024-01-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0023_alter_changetask_change_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpermission",
            name="is_profile_picture",
            field=models.BooleanField(default=False),
        ),
    ]
