# Generated by Django 4.1.1 on 2022-11-29 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0024_alter_customer_customer_profile_picture"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "UPDATE organisation SET organisation_profile_picture=null WHERE 1=1"
                )
            ]
        ),
        migrations.AlterField(
            model_name="organisation",
            name="organisation_profile_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.document",
            ),
        ),
    ]
