# Generated by Django 5.0.1 on 2024-02-16 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0024_documentpermission_is_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listofprojectstatus",
            old_name="project_status_order",
            new_name="project_status_sort_order",
        ),
        migrations.RenameField(
            model_name="listoftaskstatus",
            old_name="task_status_order",
            new_name="task_status_sort_order",
        ),
    ]
