# Generated by Django 4.1.4 on 2022-12-26 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0025_alter_organisation_organisation_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object_assignment",
            name="opportunity",
        ),
        migrations.AddField(
            model_name="object_assignment",
            name="kanban_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.kanban_card",
            ),
        ),
        migrations.AlterField(
            model_name="change_task_block",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
