# Generated by Django 5.0.1 on 2024-03-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0026_sprint_sprintaudittable_sprintobjectassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.project",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.requirement",
            ),
        ),
    ]
