# Generated by Django 5.0.1 on 2024-03-06 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0027_alter_sprint_project_alter_sprint_requirement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprintaudittable",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.project",
            ),
        ),
        migrations.AlterField(
            model_name="sprintaudittable",
            name="requirement_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.requirementitem",
            ),
        ),
        migrations.AlterField(
            model_name="sprintaudittable",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.task",
            ),
        ),
        migrations.AlterField(
            model_name="sprintobjectassignment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.project",
            ),
        ),
        migrations.AlterField(
            model_name="sprintobjectassignment",
            name="requirement_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.requirementitem",
            ),
        ),
        migrations.AlterField(
            model_name="sprintobjectassignment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.task",
            ),
        ),
    ]
