# Generated by Django 5.0.1 on 2024-03-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0028_alter_sprintaudittable_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="sprint_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Draft", "Draft"),
                    ("Current", "Current"),
                    ("Finished", "Finished"),
                ],
                default="Draft",
                max_length=10,
            ),
        ),
    ]
