# Generated by Django 5.0.3 on 2024-05-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NearBeach", "0029_alter_userjob_job_date_objecttemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectassignment",
            name="object_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.objecttemplate",
            ),
        ),
    ]
