# Generated by Django 5.0.7 on 2024-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0031_update_to_permission_sets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="permissionset",
            old_name="kanban_comment",
            new_name="kanban_note",
        ),
        migrations.RenameField(
            model_name="permissionset",
            old_name="project_history",
            new_name="project_note",
        ),
        migrations.RenameField(
            model_name="permissionset",
            old_name="task_history",
            new_name="task_note",
        ),
        migrations.AddField(
            model_name="permissionset",
            name="requirement_item_note",
            field=models.IntegerField(
                choices=[(0, "No Permission"), (1, "Has Permission")], default=0
            ),
        ),
        migrations.AddField(
            model_name="permissionset",
            name="requirement_note",
            field=models.IntegerField(
                choices=[(0, "No Permission"), (1, "Has Permission")], default=0
            ),
        ),
    ]
