# Generated by Django 5.0.7 on 2024-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0033_permissionset_organisation_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagassignment",
            name="object_enum",
            field=models.CharField(
                choices=[
                    ("requirement", "Requirement"),
                    ("requirement_item", "Requirement Item"),
                    ("project", "Project"),
                    ("task", "Task"),
                    ("kanban_board", "Kanban Board"),
                    ("kanban_card", "Kanban Card"),
                    ("request_for_change", "Request for Change"),
                    ("customer", "Customer"),
                    ("organisation", "Organisation"),
                ],
                default="requirement",
                max_length=40,
            ),
        ),
    ]
