# Generated by Django 5.0.7 on 2024-11-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0034_alter_tagassignment_object_enum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changetask",
            name="change_task_description",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_url_location",
            field=models.TextField(blank=True, default=""),
        ),
    ]
