# Generated by Django 5.0.7 on 2024-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0035_alter_changetask_change_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changetask",
            name="change_task_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
