# Generated by Django 5.0.7 on 2024-12-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0036_alter_changetask_change_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_purged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documentpermission",
            name="is_purged",
            field=models.BooleanField(default=False),
        ),
    ]
