# Generated by Django 5.1.4 on 2025-01-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0037_document_is_purged_documentpermission_is_purged"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_priority",
            field=models.IntegerField(
                choices=[
                    (0, "Highest"),
                    (1, "High"),
                    (2, "Normal"),
                    (3, "Low"),
                    (4, "Lowest"),
                ],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="requirementitem",
            name="requirement_item_priority",
            field=models.IntegerField(
                choices=[
                    (0, "Highest"),
                    (1, "High"),
                    (2, "Normal"),
                    (3, "Low"),
                    (4, "Lowest"),
                ],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_priority",
            field=models.IntegerField(
                choices=[
                    (0, "Highest"),
                    (1, "High"),
                    (2, "Normal"),
                    (3, "Low"),
                    (4, "Lowest"),
                ],
                default=2,
            ),
        ),
    ]
