# Generated by Django 5.1.6 on 2025-06-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0038_project_project_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_story_point_max",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_story_point_min",
        ),
        migrations.RemoveField(
            model_name="requirementitem",
            name="ri_story_point_max",
        ),
        migrations.RemoveField(
            model_name="requirementitem",
            name="ri_story_point_min",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_story_point_max",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_story_point_min",
        ),
        migrations.AddField(
            model_name="project",
            name="project_story_point",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="requirementitem",
            name="requirement_item_story_point",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="task_story_point",
            field=models.IntegerField(default=1),
        ),
    ]
