# Generated by Django 5.1.6 on 2025-06-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0039_remove_project_project_story_point_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="customer",
        ),
    ]
