# Generated by Django 5.1.6 on 2025-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0040_remove_project_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestforchange",
            name="rfc_status",
            field=models.IntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Waiting for approval"),
                    (3, "Approved"),
                    (4, "Started"),
                    (5, "Finished"),
                    (6, "Rejected"),
                    (7, "Paused"),
                    (8, "Ready for QA"),
                    (9, "Failed"),
                ]
            ),
        ),
    ]
