# Generated by Django 5.1.6 on 2025-07-21 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0041_alter_requestforchange_rfc_status"),
        ("knox", "0009_extend_authtoken_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendsAuthToken",
            fields=[
                (
                    "authtoken_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.KNOX_TOKEN_MODEL,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "change_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_change_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("knox.authtoken",),
        ),
        migrations.DeleteModel(
            name="ListOfRFCStatus",
        ),
    ]
