# Generated by Django 5.2.4 on 2025-08-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0043_permissionset_schedule_object"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupPermission",
        ),
    ]
