# Generated by Django 5.2.6 on 2025-09-26 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0044_delete_grouppermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanbancard",
            name="requirement_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="NearBeach.requirementitem",
            ),
        ),
    ]
