# Generated by Django 5.2.6 on 2025-09-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0045_kanbancard_requirement_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["customer_first_name"],
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterModelOptions(
            name="kanbanboard",
            options={
                "ordering": ["-kanban_board_id"],
                "verbose_name_plural": "Kanban Boards",
            },
        ),
        migrations.AlterModelOptions(
            name="kanbancard",
            options={
                "ordering": ["-kanban_card_id"],
                "verbose_name_plural": "Kanban Cards",
            },
        ),
        migrations.AlterModelOptions(
            name="kanbancolumn",
            options={
                "ordering": ["kanban_column_sort_number", "kanban_column_id"],
                "verbose_name_plural": "Kanban Columns",
            },
        ),
        migrations.AlterModelOptions(
            name="kanbanlevel",
            options={
                "ordering": ["kanban_level_sort_number", "kanban_level_id"],
                "verbose_name_plural": "Kanban Levels",
            },
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "ordering": ("organisation_name",),
                "verbose_name_plural": "Organisations",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-project_id"], "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="requestforchange",
            options={
                "ordering": ["-rfc_id"],
                "verbose_name_plural": "RequestForChanges",
            },
        ),
        migrations.AlterModelOptions(
            name="requirement",
            options={
                "ordering": ["-requirement_id"],
                "verbose_name_plural": "Requirements",
            },
        ),
        migrations.AlterModelOptions(
            name="requirementitem",
            options={
                "ordering": ["-requirement_item_id"],
                "verbose_name_plural": "Requirement Items",
            },
        ),
        migrations.AlterModelOptions(
            name="sprint",
            options={"ordering": ["-sprint_id"], "verbose_name_plural": "Sprints"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-task_id"], "verbose_name_plural": "Tasks"},
        ),
    ]
