# Generated by Django 5.2.6 on 2025-10-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0046_alter_customer_options_alter_kanbanboard_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objecttemplate",
            name="object_template_type",
            field=models.IntegerField(
                choices=[(0, "project"), (1, "task"), (2, "kanban_card")]
            ),
        ),
    ]
