# Generated by Django 6.0.1 on 2026-03-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0049_alter_project_end_date_alter_project_start_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tag_colour",
            new_name="colour",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="tag_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="tag_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="tag_text_colour",
            new_name="text_colour",
        ),
    ]
