# Generated by Django 6.0 on 2026-07-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "NearBeach",
            "0050_rename_tag_colour_tag_colour_rename_tag_id_tag_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sprint",
            old_name="sprint_end_date",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="sprint",
            old_name="sprint_start_date",
            new_name="start_date",
        ),
    ]
