# Generated by Django 6.0.4 on 2026-08-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NearBeach", "0051_rename_sprint_end_date_sprint_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sprint",
            old_name="sprint_status",
            new_name="status",
        ),
    ]
