# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban_comment',
            name='kanban_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.kanban_board'),
        ),
        migrations.AlterField(
            model_name='kanban_comment',
            name='kanban_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.kanban_card'),
        ),
    ]
