# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban_card',
            name='kanban_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.kanban_board'),
            preserve_default=False,
        ),
    ]
