# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_of_amount_type',
            options={'ordering': ['list_order']},
        ),
        migrations.AlterModelOptions(
            name='list_of_opportunity_stage',
            options={'ordering': ['list_order']},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
