# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_history',
            name='contact_date',
            field=models.DateTimeField(),
        ),
    ]
