# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_of_taxes',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_taxes_change_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_of_taxes',
            },
        ),
        migrations.CreateModel(
            name='products_and_services',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_or_service', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], max_length=7)),
                ('product_name', models.CharField(max_length=100)),
                ('product_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_and_services_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productsand_services',
            },
        ),
    ]
