# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_template',
            name='id',
        ),
        migrations.AddField(
            model_name='quote_template',
            name='quote_template_description',
            field=models.CharField(default='TEMP', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote_template',
            name='quote_template_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
