# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-11 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_contact',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
