# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement_item_links',
            name='requirement_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirement_item'),
            preserve_default=False,
        ),
    ]
