# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_kanban_card_kanban_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_set',
            name='kanban',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read Only'), (2, 'Edit Only'), (3, 'Add and Edit'), (4, 'Full Permission')], default=0),
        ),
    ]
