# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_template',
            name='template_css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
