# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission_set',
            table='permission_set',
        ),
    ]
