# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='to_do',
            fields=[
                ('to_do_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_do', models.CharField(max_length=255)),
                ('to_do_completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_do_change_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.project')),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.tasks')),
            ],
            options={
                'db_table': 'to_do',
            },
        ),
        migrations.AddField(
            model_name='organisations_campus',
            name='campus_latitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='organisations_campus',
            name='campus_longitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
    ]
