# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='organisations_id',
        ),
        migrations.AddField(
            model_name='campus',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers'),
        ),
        migrations.AddField(
            model_name='campus',
            name='organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
        ),
    ]
