# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='requirement_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.list_of_requirement_status'),
        ),
    ]
