# Generated by Django 2.1 on 2018-09-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_contact',
            old_name='organisations',
            new_name='organisation',
        ),
    ]
