# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='costs',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_description', models.CharField(max_length=255)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('project_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.project')),
                ('task_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.tasks')),
            ],
        ),
    ]
