# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_campus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organisations_campus',
            name='id',
        ),
        migrations.AddField(
            model_name='customers_campus',
            name='customers_campus_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisations_campus',
            name='organisations_campus_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
