# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_history',
            name='contact_attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_history/'),
        ),
    ]
