# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0002_initialise_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.permission_set')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.groups')),
            ],
        ),
    ]
