# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20180205_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_of_taxes',
            name='user_id',
        ),
    ]
