# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20170710_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_opportunity_stage',
            name='probability_success',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
