# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20170723_0619'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opportunity_next_step',
            table='opportunity_next_step',
        ),
    ]
