# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20170627_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='organisation_customers_documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_description', models.CharField(max_length=255)),
                ('document_url_location', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_uploaded_audit', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers')),
                ('document_folder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.document_folders')),
                ('organisations_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations')),
            ],
            options={
                'db_table': 'organisation_customers_documents',
            },
        ),
        migrations.RenameModel(
            old_name='documents',
            new_name='project_tasks_documents',
        ),
        migrations.AlterModelTable(
            name='project_tasks_documents',
            table='project_tasks_documents',
        ),
    ]
