# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
