# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20180712_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='organisations',
            new_name='organisations_id',
        ),
    ]
