# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0003_auto_20180321_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_access',
            fields=[
                ('api_access_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_access',
            },
        ),
    ]
