# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0003_list_of_taxes_products_and_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotes_products_and_services',
            fields=[
                ('quotes_products_and_services_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MaxValueValidator(99999999999999999999L), django.core.validators.MinValueValidator(99999999999999999999L)])),
                ('product_note', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_products_and_services_change_user', to=settings.AUTH_USER_MODEL)),
                ('products_and_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.products_and_services')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.list_of_taxes')),
            ],
            options={
                'db_table': 'quotes_products_and_services',
            },
        ),
    ]
