# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.project'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.tasks'),
        ),
    ]
