# Generated by Django 2.1 on 2018-09-06 07:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_groups_parent_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_description',
            field=tinymce.models.HTMLField(verbose_name='oppertunity_description'),
        ),
    ]
