# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0003_auto_20180805_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', tinymce.models.HTMLField(blank=True, null=True)),
                ('company_letter_head', tinymce.models.HTMLField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation_details', tinymce.models.HTMLField(blank=True, null=True)),
                ('product_line', models.TextField()),
                ('service_line', models.TextField()),
                ('payment_method', tinymce.models.HTMLField(blank=True, null=True)),
                ('footer', tinymce.models.HTMLField(blank=True, null=True)),
                ('page_layout', models.CharField(choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait')], default='Landscape', max_length=50)),
                ('margin_left', models.IntegerField(default=1)),
                ('margin_right', models.IntegerField(default=1)),
                ('margin_top', models.IntegerField(default=1)),
                ('margin_bottom', models.IntegerField(default=1)),
                ('margin_header', models.IntegerField(default=1)),
                ('margin_footer', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_template_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_template',
            },
        ),
    ]
