# Generated by Django 2.1 on 2018-12-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20181121_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object_assignment',
            old_name='kanban_baord_id',
            new_name='kanban_board_id',
        ),
    ]
