# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20180113_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_groups',
            old_name='user_group_permission',
            new_name='permission_set',
        ),
    ]
