# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_permission_set_kanban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanban_comment',
            old_name='kanban_comment',
            new_name='kanban_comment_text',
        ),
        migrations.AddField(
            model_name='kanban_comment',
            name='kanban_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.kanban_board'),
        ),
        migrations.AddField(
            model_name='permission_set',
            name='kanban_card',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read Only'), (2, 'Edit Only'), (3, 'Add and Edit'), (4, 'Full Permission')], default=0),
        ),
        migrations.AddField(
            model_name='permission_set',
            name='kanban_comment',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Has Permission')], default=0),
        ),
        migrations.AlterField(
            model_name='kanban_comment',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_comment_change_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kanban_comment',
            name='kanban_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.kanban_card'),
        ),
    ]
