# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20180312_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban_board',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirements'),
        ),
    ]
