# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 03:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_auto_20180808_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_template',
            name='template_css',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
