# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0003_requirement_item_links_requirement_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement_links',
            name='requirements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirements'),
            preserve_default=False,
        ),
    ]
