# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_kanban_board_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_permissions',
            name='requirement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirement_item'),
        ),
        migrations.AddField(
            model_name='document_permissions',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirements'),
        ),
    ]
