# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_quotes_products_and_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes_products_and_services',
            name='quote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.quotes'),
            preserve_default=False,
        ),
    ]
