# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20180114_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_set',
            name='requirement',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read Only'), (2, 'Edit Only'), (3, 'Add and Edit'), (4, 'Full Permission')], default=0),
        ),
        migrations.AddField(
            model_name='permission_set',
            name='requirement_link',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read Only'), (2, 'Edit Only'), (3, 'Add and Edit'), (4, 'Full Permission')], default=0),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='permission_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.permission_set'),
        ),
    ]
