# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20170418_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='cost_has_paid',
            field=models.CharField(choices=[('Not paid', 'Not paid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Has not paid', max_length=15),
        ),
    ]
