# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20170212_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations_campus',
            name='campus_address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisations_campus',
            name='campus_address2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisations_campus',
            name='campus_address3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisations_campus',
            name='campus_fax',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='organisations_campus',
            name='campus_phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
