# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20180821_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='quote_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.campus'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
