# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_customers_customer_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_document_description', models.CharField(max_length=255)),
                ('customer_document', models.FileField(upload_to='customer_documents/')),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('audit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers_documents',
            },
        ),
        migrations.CreateModel(
            name='organisations_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_document_description', models.CharField(max_length=255)),
                ('organisation_document', models.FileField(upload_to='organisation_documents/')),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('audit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organisations_document',
            },
        ),
        migrations.AddField(
            model_name='customers_campus',
            name='is_deleted',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5),
        ),
        migrations.AddField(
            model_name='organisations',
            name='organisation_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='organisations_documents',
            name='organisation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
        ),
        migrations.AddField(
            model_name='customers_documents',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers'),
        ),
    ]
