# Generated by Django 2.1 on 2018-12-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20181202_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_folder',
            name='change_user',
        ),
        migrations.RemoveField(
            model_name='document_folder',
            name='document_key',
        ),
        migrations.RemoveField(
            model_name='document_folder',
            name='folder_id',
        ),
        migrations.AddField(
            model_name='document_permission',
            name='folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.folder'),
        ),
        migrations.DeleteModel(
            name='document_folder',
        ),
    ]
