# Generated by Django 2.1 on 2018-12-16 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20181215_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudos',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customer'),
            preserve_default=False,
        ),
    ]
