# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20180113_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_groups',
            old_name='group_id',
            new_name='groups',
        ),
    ]
