# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_list_of_opportunity_stage_probability_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_opportunity_stage',
            name='opportunity_stage_description',
            field=models.CharField(max_length=50),
        ),
    ]
