# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_requirement_links_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement_item_links',
            old_name='requirement_item_permissions_id',
            new_name='requirement_item_links_id',
        ),
        migrations.RenameField(
            model_name='requirement_links',
            old_name='requirement_permissions_id',
            new_name='requirement_links_id',
        ),
    ]
