# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20180321_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations_campus',
            name='campus_latitude',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisations_campus',
            name='campus_longitude',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
            preserve_default=False,
        ),
    ]
