# Generated by Django 2.1 on 2018-09-30 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0004_user_want'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_weblink',
            fields=[
                ('user_weblink_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_weblink_url', models.URLField(max_length=50)),
                ('user_weblink_source', models.CharField(choices=[('0', 'Twitter'), ('1', 'Facebook'), ('2', 'Github'), ('3', 'Gitlab'), ('4', 'Website'), ('5', 'LinkedIn'), ('6', 'Staff page'), ('7', 'Other')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_weblink_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_weblink',
            },
        ),
    ]
