# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0004_auto_20170418_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_description', models.CharField(max_length=255)),
                ('document_location', models.TextField()),
                ('document_folder', models.CharField(max_length=255)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.project')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.tasks')),
            ],
        ),
        migrations.AlterModelTable(
            name='costs',
            table='costs',
        ),
    ]
