# Generated by Django 2.1 on 2018-09-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_user_weblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_weblink',
            name='user_weblink_source',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Github', 'Github'), ('Gitlab', 'Gitlab'), ('Website', 'Website'), ('LinkedIn', 'LinkedIn'), ('Staff Page', 'Staff page'), ('Other', 'Other')], max_length=50),
        ),
    ]
