# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_auto_20170627_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation_customers_documents',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers'),
        ),
    ]
