# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_auto_20180112_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote_responsible_customers',
            fields=[
                ('quote_responsible_customers_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.quotes')),
            ],
            options={
                'db_table': 'quote_responsible_customers',
            },
        ),
    ]
