# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_auto_20170626_1055'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organisations_documents',
            table='organisations_documents',
        ),
    ]
