# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_permission_set_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='customer_id',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='organisation_id',
            field=models.ForeignKey(blank=True, db_column='organisations_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
        ),
    ]
