# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_quotes_products_and_services_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes_products_and_services',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='quotes_products_and_services',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MaxValueValidator(-99999999999999999999L), django.core.validators.MinValueValidator(99999999999999999999L)]),
        ),
    ]
