# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_document_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='id',
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_key',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
