# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_auto_20170419_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_folders',
            fields=[
                ('document_folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_folder_description', models.CharField(max_length=255)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.project')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.tasks')),
            ],
        ),
    ]
