# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_auto_20180321_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations_campus',
            name='campus_latitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='organisations_campus',
            name='campus_longitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
    ]
