# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_auto_20170215_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_history',
            name='user_name',
            field=models.CharField(default='luke', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_history',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
