# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0006_auto_20180621_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organisations_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
        ),
    ]
