# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0005_costs_cost_has_paid'),
        ('NearBeach', '0006_document_folders'),
    ]

    operations = [
    ]
