# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0006_auto_20170817_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
