# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0006_auto_20180217_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='organisations_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
        ),
    ]
