# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_merge_20170425_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='cost_has_paid',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='document_folder',
        ),
        migrations.AddField(
            model_name='documents',
            name='document_folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.document_folders'),
        ),
        migrations.AddField(
            model_name='project_customers',
            name='customer_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
