# Generated by Django 2.1 on 2018-10-02 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0007_about_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote_permission',
            fields=[
                ('quote_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('all_user', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_permission_assigned_user', to=settings.AUTH_USER_MODEL)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_permission_change_user', to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.group')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.quote')),
            ],
            options={
                'db_table': 'quote_permission',
            },
        ),
    ]
