# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_auto_20180331_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_bug_client',
            name='bug_client_open_bugs',
            field=models.CharField(default="?open_status='True'", max_length=255),
            preserve_default=False,
        ),
    ]
