# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0007_remove_organisation_customers_documents_document_url_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_of_amount_type',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('amount_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_type_description', models.CharField(max_length=20)),
                ('list_order', models.IntegerField(unique=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_of_amount_type',
            },
        ),
        migrations.CreateModel(
            name='list_of_currency',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_description', models.CharField(max_length=20)),
                ('currency_short_description', models.CharField(max_length=4)),
                ('list_order', models.IntegerField(unique=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_of_currency',
            },
        ),
        migrations.CreateModel(
            name='list_of_lead_source',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('lead_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_source_description', models.CharField(max_length=20)),
                ('list_order', models.IntegerField(unique=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_of_lead_source',
            },
        ),
        migrations.CreateModel(
            name='list_of_opportunity_stage',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('opportunity_stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('opportunity_stage_description', models.CharField(max_length=20)),
                ('list_order', models.IntegerField(unique=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_of_opportunity_stage',
            },
        ),
        migrations.CreateModel(
            name='opportunity',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('opportunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('opportunity_name', models.CharField(max_length=255)),
                ('opportunity_description', models.TextField()),
                ('opportunity_amount', models.IntegerField()),
                ('opportunity_expected_close_date', models.DateField()),
                ('opportunity_success_probability', models.IntegerField()),
                ('opportunity_next_step', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('amount_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.list_of_amount_type')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.list_of_currency')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers')),
                ('lead_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.list_of_lead_source')),
                ('opportunity_stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.list_of_opportunity_stage')),
                ('organisations_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunities',
            },
        ),
    ]
