# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_tasks_history_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_history',
            old_name='user_name',
            new_name='user_infomation',
        ),
    ]
