# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_auto_20170817_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation_customers_documents',
            name='change_user',
        ),
        migrations.RemoveField(
            model_name='organisation_customers_documents',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='organisation_customers_documents',
            name='organisations_id',
        ),
        migrations.RemoveField(
            model_name='organisation_customers_documents',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='project_tasks_documents',
            name='change_user',
        ),
        migrations.RemoveField(
            model_name='project_tasks_documents',
            name='document_folder_id',
        ),
        migrations.RemoveField(
            model_name='project_tasks_documents',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project_tasks_documents',
            name='task_id',
        ),
        migrations.DeleteModel(
            name='organisation_customers_documents',
        ),
        migrations.DeleteModel(
            name='project_tasks_documents',
        ),
    ]
