# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_auto_20171130_1805'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products_and_services',
            table='products_and_services',
        ),
    ]
