# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0007_auto_20180623_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers'),
        ),
    ]
