# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_auto_20171204_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes_products_and_services',
            old_name='discount',
            new_name='discount_percent',
        ),
        migrations.AddField(
            model_name='quotes_products_and_services',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='quotes_products_and_services',
            name='discount_choice',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
