# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_auto_20170220_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks_history',
            old_name='user_name',
            new_name='user_infomation',
        ),
    ]
