# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_list_of_bug_client_bug_client_open_bugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_of_bug_client',
            old_name='bug_client_open_bugs',
            new_name='api_open_bugs',
        ),
        migrations.AddField(
            model_name='list_of_bug_client',
            name='api_search_bugs',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
