# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_auto_20170817_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='document_uploaded_audit',
        ),
    ]
