# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_auto_20170425_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_customers',
            name='customers_description',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
