# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_list_of_amount_type_list_of_currency_list_of_lead_source_list_of_opportunity_stage_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
