# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0008_project_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='organisations_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
        ),
    ]
