# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0009_auto_20171208_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes_products_and_services',
            name='discount_choice',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='PERCENTAGE', max_length=10),
        ),
    ]
