# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0009_auto_20170220_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='organisation_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
            preserve_default=False,
        ),
    ]
