# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0009_tasks_customers_customers_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_customers',
            name='tasks_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.tasks'),
            preserve_default=False,
        ),
    ]
