# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0010_tasks_customers_tasks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_folders',
            name='parent_folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.document_folders'),
        ),
    ]
