# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0010_auto_20170830_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_history',
            name='contact_attachment',
        ),
        migrations.AddField(
            model_name='contact_history',
            name='document_key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='NearBeach.documents'),
            preserve_default=False,
        ),
    ]
