# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0010_auto_20180704_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='requirement_permissions',
            fields=[
                ('requirement_permissions_id', models.AutoField(primary_key=True, serialize=False)),
                ('all_users', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_permissions_assigned_user', to=settings.AUTH_USER_MODEL)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_permissions_change_user', to=settings.AUTH_USER_MODEL)),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.groups')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirements')),
            ],
            options={
                'db_table': 'requirement_permission',
            },
        ),
    ]
