# Generated by Django 2.1 on 2018-10-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0010_auto_20181015_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_weblink',
            name='user_weblink_url',
            field=models.URLField(max_length=255),
        ),
    ]
