# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0010_auto_20171208_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes_products_and_services',
            name='product_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
