# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0011_permission_set_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.opportunity'),
        ),
    ]
