# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0011_document_folders_parent_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
