# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0011_auto_20170221_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='is_deleted',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5),
        ),
    ]
