# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0012_to_do_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity_permissions',
            name='user_id',
        ),
    ]
