# Generated by Django 2.1 on 2018-11-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0012_kanban_board_group_quote_group_requirement_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_user',
            name='kanban_board_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.kanban_board'),
        ),
        migrations.AddField(
            model_name='assigned_user',
            name='quote_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.quote'),
        ),
        migrations.AddField(
            model_name='assigned_user',
            name='requirement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.requirement'),
        ),
    ]
