# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0012_auto_20171208_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes_products_and_services',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='list_of_taxes',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
