# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0012_opportunity_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity_permissions',
            old_name='groups',
            new_name='groups_id',
        ),
        migrations.RenameField(
            model_name='opportunity_permissions',
            old_name='opportunity',
            new_name='opportunity_id',
        ),
    ]
