# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0013_remove_opportunity_permissions_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity_next_step',
            name='user_id',
        ),
    ]
