# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0013_auto_20171008_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity_permissions',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='opportunity_permissions',
            name='assigned_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_permissions_assigned_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
