# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0013_auto_20180710_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_history',
            name='task_history',
            field=models.TextField(),
        ),
    ]
