# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0013_auto_20170514_1456'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document_folders',
            table='document_folder',
        ),
        migrations.AlterModelTable(
            name='documents',
            table='documents',
        ),
    ]
