# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 18:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0013_auto_20171215_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes_products_and_services',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
