# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0014_auto_20170531_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_history',
            fields=[
                ('contact_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_date', models.DateField()),
                ('notes', models.TextField()),
                ('audit_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
            ],
            options={
                'db_table': 'contact_history',
            },
        ),
        migrations.CreateModel(
            name='list_of_contact_types',
            fields=[
                ('contact_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=10)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
            ],
            options={
                'db_table': 'list_of_contact_types',
            },
        ),
        migrations.AddField(
            model_name='contact_history',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.list_of_contact_types'),
        ),
        migrations.AddField(
            model_name='contact_history',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.customers'),
        ),
        migrations.AddField(
            model_name='contact_history',
            name='organisations_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
        ),
        migrations.AddField(
            model_name='contact_history',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
