# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0014_auto_20171008_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity_permissions',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_permissions_assigned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
