# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0014_remove_opportunity_next_step_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity_next_step',
            name='change_user',
        ),
        migrations.RemoveField(
            model_name='opportunity_next_step',
            name='opportunity_id',
        ),
        migrations.DeleteModel(
            name='opportunity_next_step',
        ),
    ]
