# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0015_auto_20171008_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_history',
            name='document_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.documents'),
        ),
    ]
