# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 10:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0015_auto_20171220_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes_products_and_services',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
