# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 06:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0016_auto_20171022_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_opportunity',
            fields=[
                ('project_opprtunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('opportunity_description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_opportunity_change_user', to=settings.AUTH_USER_MODEL)),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.opportunity')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.project')),
            ],
            options={
                'db_table': 'project_opportunity',
            },
        ),
    ]
