# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0017_project_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks_opportunity',
            fields=[
                ('tasks_opportunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_opportunity_change_user', to=settings.AUTH_USER_MODEL)),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.opportunity')),
                ('tasks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.tasks')),
            ],
            options={
                'db_table': 'tasks_opportunity',
            },
        ),
    ]
