# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0017_auto_20180512_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_contact',
            name='customers',
        ),
        migrations.AddField(
            model_name='email_contact',
            name='bcc_customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_contact_bcc_customers', to='NearBeach.customers'),
        ),
        migrations.AddField(
            model_name='email_contact',
            name='cc_customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_contact_cc_customers', to='NearBeach.customers'),
        ),
        migrations.AddField(
            model_name='email_contact',
            name='to_customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_contact_to_customers', to='NearBeach.customers'),
        ),
    ]
