# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 05:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0017_auto_20171226_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes_products_and_services',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
