# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NearBeach', '0018_tasks_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote_approval_status',
            fields=[
                ('quote_approval_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_approval_status', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_approval_status_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_approval_status',
            },
        ),
        migrations.CreateModel(
            name='quote_stages',
            fields=[
                ('quote_stages_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_stage', models.CharField(max_length=50)),
                ('is_invoice', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_stages_change_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_stages',
            },
        ),
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_title', models.CharField(max_length=255)),
                ('quote_valid_till', models.DateTimeField()),
                ('is_invoice', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5)),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_change_user', to=settings.AUTH_USER_MODEL)),
                ('opportunity_id', models.ForeignKey(blank=True, db_column='opportunity_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.opportunity')),
                ('project_id', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.project')),
                ('quote_approval_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.quote_approval_status')),
                ('quote_stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NearBeach.quote_stages')),
                ('task_id', models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.tasks')),
            ],
            options={
                'db_table': 'quotes',
            },
        ),
    ]
