# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0018_auto_20180516_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_contact',
            name='organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NearBeach.organisations'),
        ),
    ]
