# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 05:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0018_auto_20180103_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes_products_and_services',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
