# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0019_quote_approval_status_quote_stages_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='quote_terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
