# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeach', '0021_auto_20171127_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_quote_approval_status',
            name='quote_approved',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=5),
        ),
    ]
